# Generated by Django 6.0.3 on 2026-03-31 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отображаемое имя'),
        ),
    ]
