# Generated by Django 6.0.3 on 2026-03-31 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dialog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog_type', models.CharField(choices=[('teacher_student', 'Репетитор ↔ Ученик'), ('admin_parent', 'Админ ↔ Родитель'), ('admin_teacher', 'Админ ↔ Репетитор')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.studygroup')),
            ],
        ),
        migrations.CreateModel(
            name='DialogMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dialog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dialog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dialog')),
                ('displayed_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='displayed_messages', to=settings.AUTH_USER_MODEL)),
                ('real_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
